server:
  port: ${port:80}
spring:
  datasource:
    url: jdbc:mysql://172.16.170.49/jvm-mock?characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
mybatis:
  type-aliases-package: io.github.firefang.mock.server.entity.domain