server:
  port: ${port:80}
spring:
  datasource:
    url: jdbc:mysql://172.16.170.49/smartet
    username: root
    password: 123456
mybatis:
  type-aliases-package: io.github.firefang.mock.server.entity.domain